# Generated by Django 4.1.5 on 2023-01-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_resume', '0010_alter_baseresumepage_resume_and_more'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('baseresumepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtail_resume.baseresumepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtail_resume.baseresumepage',),
        ),
    ]
